### ISSUE TITLE
Redis object got conflicted

### ISSUE THREAD

**Issue by hckhanh** [upstash/ratelimit-js#125] opened 2024-10-17 09:26 UTC
I get this error when try to use this package

```shell
src/lib/upstash.ts:15:3 - error ts(2322): Type 'import("/Users/khanh/RustRoverProjects/sshare/node_modules/@upstash/redis/nodejs").Redis' is not assignable to type 'Redis'.
  The types returned by 'multi()' are incompatible between these types.

15   redis: ratelimitRedis,
     ~~~~~
```

```ts
import { Ratelimit } from '@upstash/ratelimit'
import { Redis } from '@upstash/redis/cloudflare'
import {
  UPSTASH_RATELIMIT_REDIS_TOKEN,
  UPSTASH_RATELIMIT_REDIS_URL,
} from 'astro:env/server'

export const ratelimitRedis = new Redis({
  token: UPSTASH_RATELIMIT_REDIS_TOKEN,
  url: UPSTASH_RATELIMIT_REDIS_URL,
  enableTelemetry: false,
})

export const verifyPasswordRatelimit = new Ratelimit({
  redis: ratelimitRedis,
  limiter: Ratelimit.slidingWindow(10, '10 s'),
  prefix: 'verify-password',
  analytics: true,
})
```

## package.json

```package.json
    "@upstash/ratelimit": "2.0.3",
    "@upstash/redis": "1.34.3",
```

**Comment by CahidArda** [comment] 2024-10-23 09:00
Hi @hckhanh,

Can you try using the latest Upstash Redis release? we bumped Upstash Redis which should fix the issue.

**Comment by hckhanh** [comment] 2024-10-23 14:28
Hi @CahidArda, thank you.

It's fixed now.

**Comment by hckhanh** [comment] 2024-10-24 01:07
@CahidArda I got another error:

```sh
src/lib/upstash.ts:19:3 - error ts(2322): Type 'import("/home/runner/work/sshare/sshare/node_modules/@upstash/redis/cloudflare").Redis' is not assignable to type 'Redis'.
  The types returned by 'multi()' are incompatible between these types.

19   redis: ratelimitRedis,
     ~~~~~
```

**Comment by hckhanh** [comment] 2024-10-24 01:09
For now, I have to cast to `never` to make the compilation go through

**Comment by hckhanh** [comment] 2024-10-24 01:11
Do you think that `@upstash/redis` should be declared as a peer dependency?

**Comment by ytkimirti** [comment] 2024-10-24 05:32
Hey @hckhanh, you are right, it should be a peer dependency but it should not cause any problems.

Can you share your ratelimit and redis versions? I couldn't reproduce it with their latest releases

**Comment by hckhanh** [comment] 2024-10-24 06:46
Here is my config:

# package.json

```
    "@upstash/ratelimit": "2.0.4",
    "@upstash/redis": "1.34.3",
```

# tsconfig.json

```tsconfig.json
{
  "extends": "astro/tsconfigs/strict",
  "compilerOptions": {
    "jsx": "react-jsx",
    "jsxImportSource": "react",
    "baseUrl": ".",
    "paths": {
      "@/*": ["./src/*"]
    }
  }
}
```

**Comment by ytkimirti** [comment] 2024-10-24 09:26
@hckhanh I still can't reproduce it. Here is the code i tested with. Can you share a codesanbox link? I am not sure what we are doing differently here

```js
import { Ratelimit } from "@upstash/ratelimit";
import { Redis } from "@upstash/redis/cloudflare";

const redis = Redis.fromEnv();

const ratelimit = new Ratelimit({
  limiter: Ratelimit.fixedWindow(10, "10s"),
  redis: redis,
});

console.log(ratelimit);
```

```
dependencies:
@upstash/ratelimit 2.0.4
@upstash/redis 1.34.3
astro 4.16.7

devDependencies:
typescript 5.6.2
```

**Comment by hckhanh** [comment] 2024-10-24 12:53
Did you initialize the application with astro and run `astro check`

**Comment by ytkimirti** [comment] 2024-10-28 05:45
Yes you are right, thanks a lot for reproduction repo.

It's weird that it only happens with astro-check. I will look into it today

**Comment by hckhanh** [comment] 2024-10-29 02:22
Thanks @ytkimirti

**Comment by ytkimirti** [comment] 2024-11-01 08:00
Hey @hckhanh, I tried a few stuff and I couldn't find anything wrong with how we use peer dependencies. I opened an issue in the astro repo.

Meanwhile, a simple `// @ts-ignore` should be enough
```ts
export const ratelimit = new Ratelimit({
  // @ts-ignore
  redis: redis,
  limiter: Ratelimit.slidingWindow(10, "1 m"),
  enableProtection: true,
  analytics: true,
});
```

**Comment by hckhanh** [comment] 2024-11-01 08:13
Thank you @ytkimirti

**Comment by rafalzawadzki** [comment] 2024-11-26 10:15
The same happened to me in a NextJS project.

```
@upstash/ratelimit 2.0.4
@upstash/redis 1.34.3
```

```bash
lib/utils/rate-limiter.ts:11:3 - error TS2322: Type 'import("---/node_modules/.pnpm/@upstash+redis@1.34.3/node_modules/@upstash/redis/nodejs").Redis' is not assignable to type 'Redis'.
  The types returned by 'multi()' are incompatible between these types.
    Type 'import("---/node_modules/.pnpm/@upstash+redis@1.34.3/node_modules/@upstash/redis/zmscore-Dc6Llqgr").P<[]>' is not assignable to type 'Pipeline<[]>'.
      Types have separate declarations of a private property 'client'.

11   redis: Redis.fromEnv(),
     ~~~~~

  node_modules/.pnpm/@upstash+ratelimit@2.0.4/node_modules/@upstash/ratelimit/dist/index.d.ts:516:5
    516     redis: Redis;
            ~~~~~
    The expected type comes from property 'redis' which is declared here on type 'RegionRatelimitConfig'

lib/utils/rate-limiter.ts:17:3 - error TS2322: Type 'import("---/node_modules/.pnpm/@upstash+redis@1.34.3/node_modules/@upstash/redis/nodejs").Redis' is not assignable to type 'Redis'.
  The types returned by 'multi()' are incompatible between these types.
    Type 'import("---/node_modules/.pnpm/@upstash+redis@1.34.3/node_modules/@upstash/redis/zmscore-Dc6Llqgr").P<[]>' is not assignable to type 'Pipeline<[]>'.
      Types have separate declarations of a private property 'client'.

17   redis,
     ~~~~~

  node_modules/.pnpm/@upstash+ratelimit@2.0.4/node_modules/@upstash/ratelimit/dist/index.d.ts:516:5
    516     redis: Redis;
            ~~~~~
    The expected type comes from property 'redis' which is declared here on type 'RegionRatelimitConfig'
```

**Comment by ytkimirti** [comment] 2024-11-27 07:53
Hey @rafalzawadzki, can you share your nextjs and typescript version with us? I couldn't reproduce it

```bash
pnpm list next typescript
```

**Comment by rafalzawadzki** [comment] 2024-11-27 08:43
> Hey @rafalzawadzki, can you share your nextjs and typescript version with us? I couldn't reproduce it
> 
> 
> 
> ```bash
> 
> pnpm list next typescript
> 
> ```

after some prodding it turned out my project was still using the old package version in node_modules/.pnpm. After I deleted it, it magically resolved to the new one.

this never happened to me before so I wonder if it still may be in any way related to your package?

**Comment by ytkimirti** [comment] 2024-11-27 08:51
Hmm interesting, but in the error you shared it seems the versions are correct from the file paths. I am still unsure why this happens.

I will probably make a cast inside our sdk to prevent this from happening again

**Comment by rafalzawadzki** [comment] 2024-11-28 16:08
true! maybe it was just my IDE resolving to the wrong directory upon CMD+click in the terminal.

Nevertheless, here are the versions:
```
next 14.0.4
typescript 5.6.3
```

**Comment by CahidArda** [comment] 2024-12-06 07:15
Hi @rafalzawadzki and @hckhanh,

do you still experience the issue in ratelimi version 2.0.5?

**Comment by hckhanh** [comment] 2024-12-06 07:23
Let me check again

**Closed** 2024-12-06 12:36 UTC
